#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate references/checklist-map.md from the canonical vibecheck_v1 mapping.

Item text, severity and verification come from controls.build_framework_mapping()
— the same source the workbook and the assessment model read. Coverage tiers come
from items.SCANNER_CHECKS, which tests/test_coverage_map.py verifies against the
emit() calls in vibecheck.sh, so the map cannot drift from what the scanner
actually checks. This is a generator, so importing the authoring input is fine.

Usage: python3 scripts/gen_map.py [--check]   (run from anywhere)
"""
import argparse
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import controls  # canonical vibecheck_v1 mapping
from items import TIER_ORDER, coverage_by_item, item_count

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO_ROOT, "references", "checklist-map.md")

cov = coverage_by_item()
n_items = item_count()

# The map renders from the canonical vibecheck_v1 framework mapping (the lossless
# projection of items.py), so item text, verification and coverage cannot drift
# from what the workbook and the assessment model consume.
_mapping = controls.build_framework_mapping()
rows = []
for e in sorted(_mapping["entries"], key=lambda e: e["item_number"]):
    n = e["item_number"]
    vcodes = e["verification"]["codes"]
    tools = e["verification"]["tools"].replace("<script>", "&lt;script&gt;")
    rows.append((n, e["category"]["en"], e["severity"], cov[n],
                 " + ".join(vcodes), tools, e["wording"]["tech_en"]))

counts = collections.Counter(cov.values())

hdr = """# Checklist item map (%d items, workbook v0.3)

Generated by `scripts/gen_map.py` from the canonical vibecheck_v1 framework mapping
(`schema/mappings/vibecheck_v1.json`, generated from `scripts/items.py`) — the same source the
workbook and the canonical assessment model consume. Do not edit this file by hand.
The workbook renders two profiles from the same bank: **reviewer** (technical wording,
Pass/Partial/Fail/Not tested/N/A, weighted gates) and **founder** (plain-question wording,
Pass/Fail/N/A, simplified verdict). Item numbers are identical in both.

Severity weights (reviewer profile): Critical=5, High=3, Medium=2, Low=1. "Triage" rows
(EU AI Act screening) carry weight 0 and are excluded from all scores in both profiles.

`scan` = what the scanner contributes for that item. Regex/path heuristics generally prove
neither a vulnerability nor its absence, and the tiers say so:

- **DECISIVE** — reserved for conclusive automation. The bundled scanner currently has none.
- **EVIDENCE** — the check surfaces material; a human decides the item either way.
- **MANUAL** — no scanner signal; the item is listed as an explicit reviewer to-do so it
  cannot be silently skipped.

| # | Category | Severity | scan | Verification | Tools | EN (technical) |
|---|----------|----------|------|--------------|-------|----------------|
""" % n_items

body = "".join("| %d | %s | %s | %s | %s | %s | %s |\n" % r for r in rows)

tail = """
## Verdict gates (reviewer profile)

NOT REVIEWED -> INCOMPLETE REVIEW (unreviewed Crit/High, N/A without reason, open screening,
unsupported Crit/High Pass, or coverage < 100%%) -> BLOCK (any Critical fail or Critical marked Accepted)
-> BLOCK - RISK ACCEPTANCE REQUIRED (any High fail) -> FIX BEFORE RELEASE (any other Fail/Partial)
-> REVIEW COMPLETE - NO OPEN FAIL/PARTIAL. Pass-rate is prioritisation data, never a release gate.
Accepted risk (with mandatory reason) counts as reviewed, is excluded from pass-rate, clears High blocks only, and stays visible in counters.

## Verdict ladder (founder profile)

NOT REVIEWED -> REVIEW INCOMPLETE (incomplete coverage, unsupported Crit/High Pass, N/A without reason, open screening)
-> DO NOT LAUNCH (any Critical fail or accepted) -> FIX BEFORE LAUNCH (any High fail)
-> FIX BEFORE LAUNCH (any other fail) -> REVIEW COMPLETE - NO OPEN FAILURES. The percentage is supporting info only.

## Coverage summary

- DECISIVE: %d items — reserved for conclusive automation.
- EVIDENCE: %d items — the scanner contributes evidence; a human decides.
- MANUAL: %d items — reviewer judgment, live probes, dashboard checks, or external evidence.

No item is decided *Pass* by the scanner alone.

## EU AI Act note (timeline)

As of 11 August 2026, Article 50 transparency obligations apply from 2 August 2026 (with a
limited marking/detection grace period for certain systems already on the market), while the
AI Omnibus timeline puts Annex III high-risk rules at 2 December 2027 and high-risk systems
embedded in regulated products at 2 August 2028. Verify the Commission implementation
timeline and the enacted regulation at assessment time; a delayed obligation is not removed.
Items 60-63 are unscored screening questions; yes/uncertain answers escalate to a specialist.

## Estonian data residency note

Do not infer that EU-region hosting is sufficient from this checklist. GDPR/IKS, international
transfer mechanisms, controller instructions/DPAs, public-sector or essential-service rules,
health and other sector rules, and record-retention duties can all change the answer. Item 58
covers database region and subprocessors such as LLM routing; obtain legal/contractual review
for the actual data and customer context.
""" % tuple(counts[t] for t in TIER_ORDER)

rendered = hdr + body + tail
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true",
                    help="fail if the committed map differs; do not modify it")
args = parser.parse_args()
if args.check:
    try:
        with open(OUT) as fh:
            current = fh.read()
    except OSError:
        current = ""
    if current != rendered:
        print("stale: %s (run python3 scripts/gen_map.py)" %
              os.path.relpath(OUT, REPO_ROOT), file=sys.stderr)
        sys.exit(1)
    print("current: %s" % os.path.relpath(OUT, REPO_ROOT))
else:
    with open(OUT, "w") as fh:
        fh.write(rendered)
    print("wrote %d items -> %s" % (n_items, os.path.relpath(OUT, REPO_ROOT)))
