#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate references/checklist-map.md from items.py (single source of truth).

Coverage tiers come from items.SCANNER_CHECKS, which is verified against the
emit() calls in vibecheck.sh by tests/test_coverage_map.py — so the map can no
longer drift from what the scanner actually checks.

Usage: python3 scripts/gen_map.py   (run from anywhere)
"""
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from items import CATEGORIES, VERIFICATION, TIER_ORDER, coverage_by_item, item_count

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO_ROOT, "references", "checklist-map.md")

cov = coverage_by_item()
n_items = item_count()

rows = []
n = 0
for cat in CATEGORIES:
    for it in cat["items"]:
        n += 1
        vcodes, tools = VERIFICATION[n]
        rows.append((n, cat["en"], it[0], cov[n], " + ".join(vcodes), tools, it[1]))

counts = collections.Counter(cov.values())

hdr = """# Checklist item map (%d items, workbook v0.3)

Generated by `scripts/gen_map.py` from `scripts/items.py` — the single source of truth shared
with `build_workbook.py` and with the scanner's check map. Do not edit this file by hand.
The workbook renders two profiles from the same bank: **reviewer** (technical wording,
Pass/Partial/Fail/Not tested/N/A, weighted gates) and **founder** (plain-question wording,
Pass/Fail/N/A, simplified verdict). Item numbers are identical in both.

Severity weights (reviewer profile): Critical=5, High=3, Medium=2, Low=1. "Triage" rows
(EU AI Act screening) carry weight 0 and are excluded from all scores in both profiles.

`scan` = what the scanner's answer is worth for that item. A static scan can prove a failure
but never prove a pass, and the tiers say so:

- **DECISIVE** — when the check fires, the item is a Fail with no interpretation needed.
  A clean run still means only "no signal found", never a Pass.
- **EVIDENCE** — the check surfaces material; a human decides the item either way.
- **MANUAL** — no scanner signal; the item is listed as an explicit reviewer to-do so it
  cannot be silently skipped.

| # | Category | Severity | scan | Verification | Tools | EN (technical) |
|---|----------|----------|------|--------------|-------|----------------|
""" % n_items

body = "".join("| %d | %s | %s | %s | %s | %s | %s |\n" % r for r in rows)

tail = """
## Verdict gates (reviewer profile)

NOT REVIEWED -> INCOMPLETE REVIEW (unreviewed Crit/High, N/A without reason, open screening,
or coverage < 100%%) -> BLOCK (any Critical fail or Critical marked Accepted) -> BLOCK - RISK ACCEPTANCE REQUIRED (any High fail)
-> FIX BEFORE RELEASE (pass-rate < 90%%) -> RELEASE CANDIDATE. A high pass-rate never overrides a gate. Accepted risk (with mandatory reason) counts as reviewed, is excluded from pass-rate, clears High blocks only, and stays visible in counters.

## Verdict ladder (founder profile)

NOT REVIEWED -> REVIEW INCOMPLETE (any Crit/High blank, N/A without reason, open screening)
-> DO NOT LAUNCH (any Critical fail or accepted) -> FIX BEFORE LAUNCH (any High fail)
-> LOOKS READY FOR A LIMITED LAUNCH. The percentage is supporting info only.

## Coverage summary

- DECISIVE: %d items — a scanner FAIL settles the item.
- EVIDENCE: %d items — the scanner contributes evidence; a human decides.
- MANUAL: %d items — reviewer judgment, live probes, dashboard checks, or external evidence.

No item is decided *Pass* by the scanner alone.

## EU AI Act note (timeline)

The May 2026 Digital Omnibus deferred Annex III high-risk obligations to 2 December 2027, but
Article 50 transparency rules apply from August 2026, and market surveillance / governance /
sanctions chapters apply from 2 August 2026. Prohibited practices (Art. 5) enforceable since
Feb 2025. Verify current status at enforcement time; do not treat the deferral as removal.
Items 60-63 are unscored screening questions in both profiles; yes/uncertain answers escalate
to a specialist ("Needs specialist" status).

## Estonian data residency note

No Estonian statute mandates in-country storage for private-sector SaaS. Governing law is
GDPR + IKS (transfer rules outside EEA). EU-region hosting is compliant. Exceptions: public
sector / vital services (E-ITS, riigipilv), accounting-record retention (Raamatupidamise
seadus, ~7y, retrievable), sector rules (health, NIS2 via kuberturvalisuse seadus), and — most
commonly binding in practice — enterprise-customer DPAs demanding EU-only processing incl.
LLM routing (item 58 covers DB region AND LLM routing).
""" % tuple(counts[t] for t in TIER_ORDER)

with open(OUT, "w") as fh:
    fh.write(hdr + body + tail)
print("wrote %d items -> %s" % (n_items, os.path.relpath(OUT, REPO_ROOT)))
